import{a as L,S as b,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const w="50757897-a80a694250436cdde2013620b",E="https://pixabay.com/api/",v=15;async function P(r,t){const o={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:t};return(await L.get(E,{params:o})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader");let R=new b(".gallery a");const s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more","hidden");f.insertAdjacentElement("afterend",s);function S(){return s}function q(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${o.likes}</p>
        <p><b>Views</b> ${o.views}</p>
        <p><b>Comments</b> ${o.comments}</p>
        <p><b>Downloads</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){f.innerHTML=""}function $(){p.classList.remove("hidden")}function x(){p.classList.add("hidden")}function A(){s.classList.remove("hidden")}function u(){s.classList.add("hidden")}const h=document.querySelector(".form"),M=h.querySelector('input[name="search-text"]'),i=S();let l=1,y="",m=0;const O=15;h.addEventListener("submit",async r=>{r.preventDefault();const t=M.value.trim();if(!t){c.warning({message:"Please enter a search query.",position:"topRight"});return}y=t,l=1,B(),u(),await g()});i.addEventListener("click",async()=>{l+=1,await g(!0)});async function g(r=!1){$(),r&&(i.disabled=!0,i.textContent="Loading images, please wait...");try{const t=await P(y,l),{hits:o,totalHits:a}=t;if(!o.length){c.info({message:"Sorry, no images found. Try another query!",position:"topRight"}),u();return}m=a,q(o),l*O>=m?(u(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):A(),r&&_()}catch(t){c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{x(),r&&(i.disabled=!1,i.textContent="Load more")}}function _(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
