import{a as v,S as E,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();const P="50757897-a80a694250436cdde2013620b",R="https://pixabay.com/api/",x=15;async function h(t,r=1){const e={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:x};return(await v.get(R,{params:e})).data}const y=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");const $=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${e.likes}</p>
        <p><b>Views</b> ${e.views}</p>
        <p><b>Comments</b> ${e.comments}</p>
        <p><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",r),$.refresh()}function B(){y.innerHTML=""}const w=document.querySelector(".form"),T=w.querySelector('input[name="search-text"]'),M=document.querySelector(".gallery"),m=document.querySelector(".load-more"),L=document.querySelector(".loader");let f="",c=1,p=0,i=0;w.addEventListener("submit",async t=>{t.preventDefault();const r=T.value.trim();if(!r){a.warning({message:"Please enter a search query.",position:"topRight"});return}f=r,c=1,i=0,B(),q(),b();try{const e=await h(f,c);if(p=e.totalHits,!e.hits.length){a.info({message:"No images found.",position:"topRight"});return}g(e.hits),i+=e.hits.length,i<p?(await l(1e3),s(),S()):(await l(1e3),s())}catch(e){a.error({message:"Something went wrong.",position:"topRight"}),console.error(e),s()}});m.addEventListener("click",async()=>{c+=1,q(),b();try{const t=await h(f,c);g(t.hits),i+=t.hits.length,O(),i<p?(await l(1e3),s(),S()):(await l(1e3),s(),a.info({message:"You've reached the end of search results.",position:"topRight"}))}catch(t){a.error({message:"Failed to load more images.",position:"topRight"}),console.error(t),s()}});function b(){L.classList.remove("hidden")}function s(){L.classList.add("hidden")}function S(){m.classList.remove("hidden")}function q(){m.classList.add("hidden")}function O(){const t=M.querySelector(".gallery-item");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}function l(t){return new Promise(r=>setTimeout(r,t))}
//# sourceMappingURL=index.js.map
