import{a as S,S as E,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&u(h)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="50757897-a80a694250436cdde2013620b",P="https://pixabay.com/api/",R=15;async function m(o,e){const r={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:R};return(await S.get(P,{params:r})).data}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),l=document.querySelector('button[type="button"]'),x=new E(".gallery a");function b(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",e),x.refresh()}function B(){y.innerHTML=""}function L(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}function $(){l.classList.remove("hidden"),l.disabled=!1,l.textContent="Load more"}function f(){l.classList.add("hidden")}const v=document.querySelector(".form"),M=v.querySelector('input[name="search-text"]'),a=document.querySelector('button[type="button"]');let c="",d=1,p=0,i=0;v.addEventListener("submit",async o=>{if(o.preventDefault(),c=M.value.trim(),d=1,i=0,!c){n.warning({message:"Please enter a search query.",position:"topRight"});return}B(),f(),L();try{const e=await m(c,d);if(p=e.totalHits,e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(e.hits),i+=e.hits.length,i<p?$():(f(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{w()}});a.addEventListener("click",async()=>{d+=1,a.disabled=!0,a.textContent="Loading images, please wait...",L();try{const o=await m(c,d);b(o.hits),i+=o.hits.length,i>=p?(f(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):(a.disabled=!1,a.textContent="Load more");const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){n.error({message:"Failed to load more images.",position:"topRight"}),console.error(o)}finally{w()}});
//# sourceMappingURL=index.js.map
